before_script:
  - bash gitlabci/before_script.sh > /dev/null

services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: PPLA4
  MYSQL_ROOT_PASSWORD: secret

# Select image from https://hub.docker.com/r/_/php/
image: php:5.6
build:dependencies:
  script:
  - bash gitlabci/install_dependency.sh > /dev/null
  - bash gitlabci/install_phpunit.sh > /dev/null
  - bash gitlabci/install_xdebug.sh > /dev/null
  - ls -a
  - bash gitlabci/setup_database.sh

# TODO: buat test scriptnya
test:coverage:
  script:
  - vendor/bin/phpunit --coverage-text --colors=never --configuration phpunit.xml