before_script:
  - bash gitlabci/before_script.sh > /dev/null

services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: PPLA4
  MYSQL_ROOT_PASSWORD: secret
  HEROKU_API_KEY: c55dbde4-e0e8-4a06-bc92-75cac23b7ce5

# Select image from https://hub.docker.com/r/_/php/
image: php:5.6
build:dependencies:
  script:
  - bash gitlabci/install_dependency.sh > /dev/null
  - bash gitlabci/install_phpunit.sh > /dev/null
  - bash gitlabci/install_xdebug.sh > /dev/null
  - bash gitlabci/setup_database.sh
  - ls vendor
  - ls vendor/bin
  - bash gitlabci/install_ruby.sh > /dev/null

# TODO: buat test scriptnya
test:coverage:
  script:
  - vendor/bin/phpunit --coverage-text --colors=never --configuration phpunit.xml
  
 staging:
  type: deploy
  - gem install dpl
  - dpl --provider=heroku --app=jojotravel --api-key=$HEROKU_API_KEY