before_script:
# Install dependencies
- bash gitlabci/docker_install.sh > /dev/null
- bash gitlabci/composer_install.sh
- bash gitlabci/laravel_setup.sh

# Select image from https://hub.docker.com/r/_/php/
image: php:5.6

#TODO: Placeholder?
test:app:
  script:
  - phpunit --configuration phpunit_myapp.xml